#version: "4"

services:
  backend:
    build:
      context: .                # ⬅ build from repo root
      dockerfile: backend/Dockerfile
    working_dir: /code
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/code                # ⬅ mount the whole repo, not only ./backend
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    restart: unless-stopped


  mcp-osm:
    image: python:3.11-slim
    container_name: mcp-osm
    working_dir: /app
    stdin_open: true   # allow stdio tools
    tty: true
    volumes:
      - ./:/app
    command: >-
      sh -lc "pip install --no-cache-dir -r backend/requirements.txt && tail -f /dev/null"
    restart: unless-stopped

  mcp-weather:
    image: python:3.11-slim
    container_name: mcp-weather
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    volumes:
      - ./:/app
    command: >-
      sh -lc "pip install --no-cache-dir -r backend/requirements.txt && tail -f /dev/null"
    restart: unless-stopped
